# -*- coding: utf-8 -*-
"""AI Lab 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vSCQEToI7GMCpfO0alIlEe0I_Sx3Ofgh

# My Name:
"""

print("Usman Javed");

"""# Addition"""

a=1;
b=5;
print(a+b);

"""# Subtraction:"""

a=1;
b=5;
print(a-b);

"""# Multiplication:"""

a=2;
b=5;
print(a*b);

"""# Division:"""

a=10;
b=5;
print(a/b);