# -*- coding: utf-8 -*-
"""Lab2Task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L-6ra4tTWiY78VpiXkFLgu_LJmS3Jpcj

# Matplotlib

# Numpy

# List
"""

my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(my_list)
list_sum = sum(my_list)
list_max = max(my_list)
list_min = min(my_list)

print(f"Sum of the list: {list_sum}")
print(f"Maximum element in the list: {list_max}")
print(f"Minimum element in the list: {list_min}")
my_list.append(11)
print(my_list)
my_list.pop()
print(my_list)

my_list.sort()
print(my_list)

my_list.reverse()
print(my_list)

"""# Tuple"""

fruits_tuple = ("apple", "banana", "strawberry", "date", "milk")
print(fruits_tuple)

print(fruits_tuple[1])
print(fruits_tuple[-1])

my_list = list(fruits_tuple)
my_list[1] = "orange"
fruits_tuple = tuple(my_list)
print(f"Modified tuple: {fruits_tuple}")

"""# Set"""

set1 = {1, 2, 3, 4, 5, 6}
set2 = {4, 5, 6, 7, 8, 9}

print("Set 1:", set1)
print("Set 2:", set2)

union_set = set1.union(set2)
print("Union Set:", union_set)

intersection_set = set1.intersection(set2)
print("Intersection Set:", intersection_set)

difference_set = set1.difference(set2)
print("Difference Set:", difference_set)

set1.add(7)
print("Add Set:", set1)

set1.remove(3)
print("Remove Set:", set1)

"""# Dictionary"""

student_marks = {
    "Alice": 85,
    "Bob": 92,
    "Charlie": 78,
    "David": 95,
    "Eve": 88,
     "Eve": 82

}

print(student_marks)

student_marks["Bob"] = 90
print(student_marks)

del student_marks["Charlie"]
print(student_marks)